spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/probook
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    servlet:
        encoding:
            charset: UTF-8
            force: true